[package]
name = "spinon-runtime"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
spinon-core = { path = "../spinon-core" }
spinon-layout = { path = "../spinon-layout" }
spinon-style = { path = "../spinon-style" }
spinon-style-to-layout = { path = "../spinon-style-to-layout" }
spinon-style-to-render = { path = "../spinon-style-to-render" }
spinon-render = { path = "../spinon-render" }

[dev-dependencies]
serde_json = "=1.0.151"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
