duration_ms: 8000
buffers { size_kb: 16384 fill_policy: DISCARD }
data_sources {
  config {
    name: "linux.perf"
    perf_event_config {
      timebase { counter: SW_CPU_CLOCK frequency: 99 timestamp_clock: PERF_CLOCK_MONOTONIC }
      callstack_sampling {
        scope { target_cmdline: "dev.spinon.bootstrap" }
        kernel_frames: true
      }
    }
  }
}
data_sources { config { name: "android.surfaceflinger.frametimeline" } }
